pull_request_rules:
- actions:
    comment:
      message: dependabot was here
  conditions:
  - dependabot-dependency-name=bootstrap
  - dependabot-update-type=version-update:semver-minor
  name: Merge if dependabot properties are checked
