commands_restrictions:
  copy:
    conditions:
    - sender=toto
extends: .github
pull_request_rules:
- actions:
    merge: {}
  conditions:
  - base=20220905113505/test_extend_config_file_merge_ok/main
  - -merged
  name: merge on main
