commands_restrictions:
  copy:
    conditions:
    - sender=toto
extends: .github
pull_request_rules:
- actions:
    merge: {}
  conditions:
  - base=20220905121625/test_extend_config_file_merge_ok/main
  - -merged
  name: merge on main
queue_rules:
- allow_inplace_checks: false
  conditions:
  - 'schedule: MON-FRI 08:00-17:00'
  name: new_rule
