pull_request_rules:
- actions:
    queue: {}
  conditions:
  - base=20220921094641/test_queue_with_default_config_branch_protection_code_owners_ok/main
  - label=queue
  name: Merge priority high
queue_rules:
- conditions: []
  name: default
